# Generated by Django 5.0.3 on 2024-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_usermodel_remove_itemmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='crudapp\\static')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='itemmodel',
        ),
    ]
